name:                fixpoint
version:             0.1.0.0
github:              "freefrancisco/fixpoint"
license:             BSD3
author:              "Francisco Gutierrez"
maintainer:          "freefrancisco@gmail.com"
copyright:           "2018 Francisco Gutierrez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/freefrancisco/fixpoint#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck

library:
  source-dirs: src


tests:
  fixpoint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fixpoint
